name: Deploy to server

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run:
        npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_SSH_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/my-app
          rm -rf *
          tar xzvf - -C .
