name: Schedule Deploy

on:
  push:
    branches:
      - main

jobs:
  mark-deploy-needed:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "true" > deploy-flag
      - name: Upload deploy flag
        uses: actions/upload-artifact@v3
        with:
          name: deploy-flag
          path: deploy-flag
